### ISSUE TITLE
License description is incorrect

### ISSUE THREAD

**Issue by rw** [klout/opendata#4]
The DAWT readme states:

"The following datasets are licensed under a Attribution-ShareAlike 3.0 Unported same as Wikipedia Database Dumps."

The text "Attribution-ShareAlike 3.0 Unported" means `CC BY-SA 3.0` and should point to:

https://creativecommons.org/licenses/by-sa/3.0/

But instead it points to `CC BY-NC-SA 4.0`:

https://creativecommons.org/licenses/by-nc-sa/4.0/

Which license is correct? Note that the Wikipedia dumps use `CC BY-SA 2.0`.

**Comment by sofra** [comment]
Made clarification on the initial page as each data set has it's own licence. 
CL: https://github.com/klout/opendata/commit/3294a51010feb579f51d410db67fc9ff72f7597a

**Comment by rw** [comment]
So DAWT is CC BY-SA?
